# Start your image with a node base image
FROM python:3.9-slim

# The /app directory should act as the main application directory
WORKDIR /app

# Server = Master Server for all the clients
COPY master.py /app

CMD [ "python", "master.py" ]